### ISSUE TITLE
Failed to render and update auto layout status

### ISSUE THREAD

**Issue by itchix** [louisdh/huekit#1]
I get some errors like this, and in my storyboard, my view is blank. Any ideas to resolve it?

Thanks 😃 

```
Main.storyboard: error: IB Designables: Failed to render and update auto layout status for ControlLightViewController (Tlk-rF-UDK): dlopen(HueKit.framework, 1): no suitable image found.  Did find:
	HueKit.framework: required code signature missing for 'HueKit.framework'
```

**Comment by Kamik423** [comment]
same here 🙋‍♂️

**Comment by louisdh** [comment]
Might be fixed by d5b9451faaaa3c3a5f0a6c04acf55119a0820e52

**Comment by Kamik423** [comment]
Confirmed not occurring for me anymore!

**Comment by syrakozz** [comment]
same here , it`s appearing now , error: IB Designables: Failed to render and update auto layout status for UIView (i5M-Pr-FkT): dlopen(HueKit.framework, 1): no suitable image found.  Did find:
	HueKit.framework: required code signature missing for 'HueKit.framework'

**Comment by syrakozz** [comment]
ok fixed by adding  to pod

# Workaround for Cocoapods v.1.5 issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
